services:
  app:
    image: ${IMAGES_PREFIX:-miris.design}/coral:${APP_VERSION:-latest}
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-coral.miris.design}, :80

      APP_NAME: ${APP_NAME:-"Coral Bells"}
      APP_TEAM: ${APP_TEAM:-"Eastern Corals"}
      APP_ENV: ${APP_ENV:-production}
      APP_KEY: ${APP_KEY} # base64:$(head -c32 /dev/urandom | base64)
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_TIMEZONE: ${APP_TIMEZONE:-UTC}
      APP_URL: ${APP_URL:-https://coral.miris.design}

      APP_LOCALE: ${APP_LOCALE:-en}
      APP_FALLBACK_LOCALE: ${APP_FALLBACK_LOCALE:-en}
      APP_FAKER_LOCALE: ${APP_FAKER_LOCALE:-en_US}

      APP_MAINTENANCE_DRIVER: ${APP_MAINTENANCE_DRIVER:-file}
      APP_MAINTENANCE_STORE: ${APP_MAINTENANCE_STORE:-database}

      BCRYPT_ROUNDS: ${BCRYPT_ROUNDS:-12}

      LOG_CHANNEL: ${LOG_CHANNEL:-stack}
      LOG_STACK: ${LOG_STACK:-single}
      LOG_DEPRECATIONS_CHANNEL: ${LOG_DEPRECATIONS_CHANNEL:-null}
      LOG_LEVEL: ${LOG_LEVEL:-debug}

      DB_CONNECTION: ${DB_CONNECTION:-sqlite}
      # DB_HOST: ${DB_HOST:-mysql}
      # DB_PORT: ${DB_PORT:-3306}
      # DB_DATABASE: ${DB_DATABASE:-coral}
      # DB_USERNAME: ${DB_USERNAME:-coral}
      # DB_PASSWORD: ${DB_PASSWORD:-coral}

      SESSION_DRIVER: ${SESSION_DRIVER:-database}
      SESSION_LIFETIME: ${SESSION_LIFETIME:-120}
      SESSION_ENCRYPT: ${SESSION_ENCRYPT:-false}
      SESSION_PATH: ${SESSION_PATH:-/}
      SESSION_DOMAIN: ${SESSION_DOMAIN:-null}

      BROADCAST_CONNECTION: ${BROADCAST_CONNECTION:-log}
      FILESYSTEM_DISK: ${FILESYSTEM_DISK:-local}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION:-database}

      CACHE_STORE: ${CACHE_STORE:-database}
      CACHE_PREFIX: ${CACHE_PREFIX:-}

      MEMCACHED_HOST: ${MEMCACHED_HOST:-127.0.0.1}

      REDIS_CLIENT: ${REDIS_CLIENT:-phpredis}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-null}
      REDIS_PORT: ${REDIS_PORT:-6379}

      MAIL_MAILER: ${MAIL_MAILER:-smtp}
      MAIL_HOST: ${MAIL_HOST:-mailpit}
      MAIL_PORT: ${MAIL_PORT:-1025}
      MAIL_USERNAME: ${MAIL_USERNAME:-null}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-null}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION:-null}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS:-"hello@example.com"}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME:-"${APP_NAME:-coral}"}

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}
      AWS_BUCKET: ${AWS_BUCKET:-}
      AWS_USE_PATH_STYLE_ENDPOINT: ${AWS_USE_PATH_STYLE_ENDPOINT:-false}

      VITE_APP_NAME: ${VITE_APP_NAME:-"${APP_NAME:-coral}"}

      SCOUT_DRIVER: ${SCOUT_DRIVER:-meilisearch}
      MEILISEARCH_HOST: ${MEILISEARCH_HOST:-http://meilisearch:7700}

      MEILISEARCH_NO_ANALYTICS: ${MEILISEARCH_NO_ANALYTICS:-false}

      WWWGROUP: ${WWWGROUP:-1000}
      WWWUSER: ${WWWUSER:-1000}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - stack_storage:/app/storage
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    networks:
      - coral
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:80/up
      retries: 3
      timeout: 5s

networks:
  coral:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  stack_storage:
  mysql_database:
